package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"afterzin/api/internal/graphql/model"
	"context"
	"fmt"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Register - register"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// CreateEvent is the resolver for the createEvent field.
func (r *mutationResolver) CreateEvent(ctx context.Context, input model.CreateEventInput) (*model.Event, error) {
	panic(fmt.Errorf("not implemented: CreateEvent - createEvent"))
}

// UpdateEvent is the resolver for the updateEvent field.
func (r *mutationResolver) UpdateEvent(ctx context.Context, id string, input model.UpdateEventInput) (*model.Event, error) {
	panic(fmt.Errorf("not implemented: UpdateEvent - updateEvent"))
}

// PublishEvent is the resolver for the publishEvent field.
func (r *mutationResolver) PublishEvent(ctx context.Context, id string) (*model.Event, error) {
	panic(fmt.Errorf("not implemented: PublishEvent - publishEvent"))
}

// UpdateEventStatus is the resolver for the updateEventStatus field.
func (r *mutationResolver) UpdateEventStatus(ctx context.Context, id string, status model.EventStatus) (*model.Event, error) {
	panic(fmt.Errorf("not implemented: UpdateEventStatus - updateEventStatus"))
}

// CreateEventDate is the resolver for the createEventDate field.
func (r *mutationResolver) CreateEventDate(ctx context.Context, eventID string, input model.EventDateInput) (*model.EventDate, error) {
	panic(fmt.Errorf("not implemented: CreateEventDate - createEventDate"))
}

// CreateLot is the resolver for the createLot field.
func (r *mutationResolver) CreateLot(ctx context.Context, dateID string, input model.LotInput) (*model.Lot, error) {
	panic(fmt.Errorf("not implemented: CreateLot - createLot"))
}

// CreateTicketType is the resolver for the createTicketType field.
func (r *mutationResolver) CreateTicketType(ctx context.Context, lotID string, input model.TicketTypeInput) (*model.TicketType, error) {
	panic(fmt.Errorf("not implemented: CreateTicketType - createTicketType"))
}

// CheckoutPreview is the resolver for the checkoutPreview field.
func (r *mutationResolver) CheckoutPreview(ctx context.Context, input model.CheckoutInput) (*model.CheckoutPreviewResult, error) {
	panic(fmt.Errorf("not implemented: CheckoutPreview - checkoutPreview"))
}

// CheckoutPay is the resolver for the checkoutPay field.
func (r *mutationResolver) CheckoutPay(ctx context.Context, input model.CheckoutPayInput) (*model.CheckoutPayResult, error) {
	panic(fmt.Errorf("not implemented: CheckoutPay - checkoutPay"))
}

// UpdateProfilePhoto is the resolver for the updateProfilePhoto field.
func (r *mutationResolver) UpdateProfilePhoto(ctx context.Context, photoBase64 string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UpdateProfilePhoto - updateProfilePhoto"))
}

// UpdatePhone is the resolver for the updatePhone field.
func (r *mutationResolver) UpdatePhone(ctx context.Context, phoneCountryCode string, phoneAreaCode string, phoneNumber string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UpdatePhone - updatePhone"))
}

// ValidateTicket is the resolver for the validateTicket field.
func (r *mutationResolver) ValidateTicket(ctx context.Context, eventID string, qrCode string) (*model.ValidateTicketResult, error) {
	panic(fmt.Errorf("not implemented: ValidateTicket - validateTicket"))
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, filter *model.EventFilter) ([]*model.Event, error) {
	panic(fmt.Errorf("not implemented: Events - events"))
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, id string) (*model.Event, error) {
	panic(fmt.Errorf("not implemented: Event - event"))
}

// ProducerEvents is the resolver for the producerEvents field.
func (r *queryResolver) ProducerEvents(ctx context.Context) ([]*model.Event, error) {
	panic(fmt.Errorf("not implemented: ProducerEvents - producerEvents"))
}

// ProducerPublicProfile is the resolver for the producerPublicProfile field.
func (r *queryResolver) ProducerPublicProfile(ctx context.Context, producerID string) (*model.ProducerPublicProfile, error) {
	panic(fmt.Errorf("not implemented: ProducerPublicProfile - producerPublicProfile"))
}

// MyTickets is the resolver for the myTickets field.
func (r *queryResolver) MyTickets(ctx context.Context) ([]*model.Ticket, error) {
	panic(fmt.Errorf("not implemented: MyTickets - myTickets"))
}

// MyTicket is the resolver for the myTicket field.
func (r *queryResolver) MyTicket(ctx context.Context, id string) (*model.Ticket, error) {
	panic(fmt.Errorf("not implemented: MyTicket - myTicket"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// ProducerMe is the resolver for the producerMe field.
func (r *queryResolver) ProducerMe(ctx context.Context) (*model.Producer, error) {
	panic(fmt.Errorf("not implemented: ProducerMe - producerMe"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
